name: Build macOS App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest  # Use the macOS runner

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Checks out your code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt  # Install dependencies from requirements.txt if you have one

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile autoclicker.py
          # Replace 'autoclicker.py' with your main script name

      - name: Upload macOS App
        uses: actions/upload-artifact@v2
        with:
          name: macos-autoclicker
          path: dist/autoclicker  # Path to the compiled .app file or executable

